name: Django CI

on:
  push:
    branches:
      - master
      - main
      - dev
  pull_request:
    branches:
      - master
      - main
      - dev

env:
  APP_PATH: tools
  DEP_PATH: tools
  ENV_TYPE: venv
  FAIL_LEVEL: WARNING
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.python-version }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, python-version: '3.6'}
          - {os: ubuntu-latest, python-version: '3.7'}
          - {os: ubuntu-latest, python-version: '3.8'}
          - {os: ubuntu-latest, python-version: '3.9'}
    steps:
    - uses: actions/checkout@v2
    - name: Install System Dependencies
      run: sudo apt-get install python3-testresources
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tools/requirements.txt
        pip install coverage coveralls
    - name: Scan Django settings for security issues
      id: check
      uses: victoriadrake/django-security-check@master
    - id: results
      run: |
        OUTPUT=$(cat output.txt)
        FORMATTED=${OUTPUT//$'\n'/%0A}
        echo ::set-output name=file::**Django Security Check identified issues:** %0A$FORMATTED
    - name: Comment with output
      uses: actions/github-script@v3
      with:
       script: |
         github.issues.createComment({
           issue_number: ${{ github.event.number }},
           owner: context.repo.owner,
           repo: context.repo.repo,
           body: `${{ steps.results.outputs.file }}`
         })
    - name: Run Tests
      run: |
        coverage run --omit=*/tests/* ${APP_PATH)/manage.py test
    - name: Coveralls
      if: matrix.config.os  == 'ubuntu-latest' && matrix.python-version == '3.7'
      run: coveralls --service=github

