name: Django Security Check (on pull-request "base" branch)

on: [pull_request_target]

env:
  FAIL_LEVEL: WARNING
  ENV_TYPE: venv
  APP_PATH: tools/
  DEP_PATH: tools/requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Scan Django settings for security issues
        id: check
        uses: mrustl/django-security-check@master
      - id: results
        run: |
          OUTPUT=$(cat ${{ github.workspace }}/${{ env.APP_PATH}}/output.txt)
          FORMATTED=${OUTPUT//$'\n'/%0A}
          echo ::set-output name=file::**Django Security Check identified issues:** %0A$FORMATTED
      - name: Comment with output
        uses: actions/github-script@v3
        with:
          script: |
            github.issues.createComment({
              issue_number: ${{ github.event.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${{ steps.results.outputs.file }}`
            })
